### ISSUE TITLE
The DarrynTen\Clarifai\Clarifai::getModel() Does not exist error.

### ISSUE THREAD

**Issue by abhishek6262** [darrynten/clarifai-php#32]
Hello,

On making the call with the given code below, the code always returns an error that the "getModel" method doesn't exist. Moreover "\DarrynTen\Clarifai\Repository\Model::GENERAL" this also is not found. Is there any fix to this problem?

```
$clarifai = new Clarifai($this->clientId, $this->clientSecret);

$modelResult = $clarifai->getModel()->predictUrl(
    'https://samples.clarifai.com/metro-north.jpg',
     \DarrynTen\Clarifai\Repository\Model::GENERAL
);
```

**Comment by vojtik** [comment]
Hello.
Try `$clarifai->getModelRepository()` instead of `$clarifai->getModel()`.
It’s a part of old documentation we missed to fix. Thanks for letting us know!

**Comment by abhishek6262** [comment]
Yeah @vojtik , on exploring through the code of the package I found that the package has `getModelRepository` method instead of `getModel` method. Moreover given below is the working solution for the error above if in future someone else experiences it.

```
$clarifai = new Clarifai('clientId', 'clientSecret');

$modelResult = $clarifai->getModelRepository()->predictUrl(
    'https://samples.clarifai.com/metro-north.jpg',
    \DarrynTen\Clarifai\Repository\ModelRepository::GENERAL
);
```
Thanks :)

**Comment by mxnr** [comment]
Fix merged to master, thanks guys!
